package main

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
Find the sum of all the even-valued terms in the sequence which do not exceed four million.
*/

import "fmt"



func main (){

	var a int = 1
    var	b int = 1
    var c int = 0
	result := 0
	
	for {
		c = a + b
		a = b
		b = c
		if c % 2 == 0 {
			result += c
		}
		if c >= 4000000 {
			fmt.Printf("result: %v\n",result)
			return
		}	
	}
}

/*
	result: 4613732
*/